import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from "@/components/banner/banner";
import NavBar from "@/components/nav/navBar";
import Card from "@/components/card/card";
import SectionCards from "@/components/card/section-cards";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    const pelisVideos = [
        {
            imgUrl: '/static/upMovie.webp'
        },
        {
            imgUrl: '/static/upMovie.webp'
        },
    ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <NavBar username={'edgar'}/>
      <Banner title='Up' subTitle='adventure' imgUrl='/static/upMovie.webp'/>

      <div className={styles.sectionWrapper}>
          <SectionCards title={'Pelis'} videos={pelisVideos} size={'large'}/>
          <SectionCards title={'Pelis'} videos={pelisVideos} size={'medium'}/>
      </div>

    </div>
  )
}
